# Demo data for BookWise E-commerce without database
DEMO_USERS = {
    "client@bookwise.com": {
        "id": 1,
        "first_name": "João",
        "last_name": "Silva", 
        "email": "client@bookwise.com",
        "password": "client123",  # In production, this would be hashed
        "phone": "(11) 98765-4321",
        "cpf": "123.456.789-01",
        "birthday": "1990-05-15",
        "user_type": "client",
        "user_type_id": 2,
        "gender": "Masculino",
        "is_active": True,
        "address": {
            "zip_code": "01234-567",
            "street": "Rua das Flores, 123",
            "number": "123",
            "complement": "Apto 45",
            "neighborhood": "Centro",
            "city": "São Paulo",
            "state": "SP",
            "country": "Brasil"
        },
        "created_at": "2024-01-15T10:30:00Z"
    },
    "admin@bookwise.com": {
        "id": 2,
        "first_name": "Admin",
        "last_name": "User", 
        "email": "admin@bookwise.com",
        "password": "admin123",  # In production, this would be hashed
        "phone": "11987654321",
        "user_type": "admin",
        "is_active": True
    },
    "testuser@bookwise.com": {
        "id": 3,
        "first_name": "Test",
        "last_name": "User", 
        "email": "testuser@bookwise.com",
        "password": "123456",  # In production, this would be hashed
        "phone": "11999887766",
        "user_type": "client",
        "is_active": True
    }
}

DEMO_BOOKS = [
    {
        "id": "1",
        "title": "Clean Code: A Handbook of Agile Software Craftsmanship",
        "author": "Robert C. Martin",
        "year": "2008", 
        "isbn": "9780132350884",
        "edition": "1st Edition",
        "origin": "USA",
        "book_format": "Paperback",
        "binding": "Perfect Bound",
        "language": "English",
        "country": "United States",
        "pages": "464",
        "stock": "15",
        "url_img": "https://picsum.photos/300/400?random=1",
        "description": "Even bad code can function. But if code isn't clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn't have to be that way.",
        "price": "45.99",
        "category": "Programming",
        "rating": "4.8",
        "featured": True,
        "bestseller": True
    },
    {
        "id": "2", 
        "title": "Design Patterns: Elements of Reusable Object-Oriented Software",
        "author": "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
        "year": "1994",
        "isbn": "9780201633610", 
        "edition": "1st Edition",
        "origin": "USA",
        "book_format": "Hardcover",
        "binding": "Hardbound",
        "language": "English", 
        "country": "United States",
        "pages": "395",
        "stock": "8",
        "url_img": "https://picsum.photos/300/400?random=2",
        "description": "Capturing a wealth of experience about the design of object-oriented software, four top-notch designers present a catalog of simple and succinct solutions to commonly occurring design problems.",
        "price": "59.99", 
        "category": "Programming",
        "rating": "4.6",
        "featured": True,
        "bestseller": False
    },
    {
        "id": "3",
        "title": "The Pragmatic Programmer: Your Journey To Mastery", 
        "author": "Andrew Hunt, David Thomas",
        "year": "2019",
        "isbn": "9780135957059",
        "edition": "2nd Edition", 
        "origin": "USA",
        "book_format": "Paperback",
        "binding": "Perfect Bound",
        "language": "English",
        "country": "United States", 
        "pages": "352",
        "stock": "12",
        "url_img": "https://picsum.photos/300/400?random=3",
        "description": "Ward Cunningham Straight from the programming trenches, The Pragmatic Programmer cuts through the increasing specialization and technicalities of modern software development to examine the core process--taking a requirement and producing working, maintainable code.",
        "price": "42.99",
        "category": "Programming",
        "rating": "4.7",
        "featured": False,
        "bestseller": True
    },
    {
        "id": "4",
        "title": "JavaScript: The Definitive Guide",
        "author": "David Flanagan",
        "year": "2020", 
        "isbn": "9781491952023",
        "edition": "7th Edition",
        "origin": "USA",
        "book_format": "Paperback",
        "binding": "Perfect Bound",
        "language": "English",
        "country": "United States",
        "pages": "706",
        "stock": "20",
        "url_img": "https://picsum.photos/300/400?random=4",
        "description": "JavaScript is the programming language of the web and is used by more software developers today than any other programming language. For nearly 25 years this best seller has been the go-to guide for JavaScript programmers.",
        "price": "52.99",
        "category": "Web Development",
        "rating": "4.5",
        "featured": True,
        "bestseller": True
    },
    {
        "id": "5",
        "title": "Python Crash Course: A Hands-On, Project-Based Introduction",
        "author": "Eric Matthes",
        "year": "2019", 
        "isbn": "9781593279288",
        "edition": "2nd Edition",
        "origin": "USA",
        "book_format": "Paperback",
        "binding": "Perfect Bound",
        "language": "English",
        "country": "United States",
        "pages": "544",
        "stock": "25",
        "url_img": "https://picsum.photos/300/400?random=5",
        "description": "Python Crash Course is the world's best-selling Python book. A fast-paced, thorough introduction to programming with Python that will have you writing programs, solving problems, and making things that work in no time.",
        "price": "38.99",
        "category": "Programming",
        "rating": "4.9",
        "featured": True,
        "bestseller": True
    },
    {
        "id": "6",
        "title": "System Design Interview: An Insider's Guide",
        "author": "Alex Xu",
        "year": "2020", 
        "isbn": "9798664653403",
        "edition": "1st Edition",
        "origin": "USA",
        "book_format": "Paperback",
        "binding": "Perfect Bound",
        "language": "English",
        "country": "United States",
        "pages": "322",
        "stock": "18",
        "url_img": "https://picsum.photos/300/400?random=6",
        "description": "The system design interview is considered to be the most complex and most difficult technical job interview by many. This book provides a step-by-step framework on how to tackle a system design question.",
        "price": "35.99",
        "category": "System Design",
        "rating": "4.7",
        "featured": False,
        "bestseller": True
    }
]

DEMO_CART = {}  # Will store cart items by user session