from model.book import Book

books = [
    Book(
        title="The Hunger Games",
        author="Suzanne Collins",
        year='2008',
        isbn="9780439023481",
        edition="1st",
        origin="USA",
        book_format="ebook",
        binding="Sewn Binding",
        language="English",
        country="United States",
        pages='384',
        stock='100',
        url_img="https://m.media-amazon.com/images/I/414fBKKVniL._SY344_BO1,204,203,200_QL70_ML2_.jpg",
        description="In A Dystopian North America Katniss Volunteers To Compete In A Televised Survival "
                    "Game Replacing Her Younger Sister The Game Is Run By The Rulers Of Panem To Maintain "
                    "Control Over The Twelve Districts.",
        price='22.45',
        category="Adventure"
        ),
    Book(
        title="The Da Vinci Code",
        author="Dan Brown",
        year='2003',
        isbn="9780307474278",
        edition="1st", origin="USA",
        book_format="ebook",
        binding="Perfect Binding",
        language="English",
        country="United States",
        pages='689',
        stock='50',
        url_img="https://m.media-amazon.com/images/I/51hYdKyWYqL._SY346_.jpg",
        description="Professor Robert Langdon And Cryptographer Sophie Neve Must Decipher A Deadly "
                    "Web Of Deceit Involving The Works Of Leonardo Da Vinci After The Curator Of The "
                    "Louvre Is Found Murdered In The Museums Halls.",
        price='12.13',
        category="Adventure"
        ),
    Book(
        title="The Lord of the Rings: The Fellowship of the Ring",
        author="J.R.R. Tolkien",
        year='1954',
        isbn="9780547928210",
        edition="1st",
        origin="United Kingdom",
        book_format="ebook",
        binding="Sewn Binding",
        language="English",
        country="United Kingdom",
        pages='432',
        stock='80',
        url_img="https://m.media-amazon.com/images/I/61mn09OvTQL._AC_UY327_FMwebp_QL65_.jpg",
        description="The First Volume In Jrr Tolkiens Epic Adventure The Lord Of The Rings One Ring To Rule "
                    "Them All One Ring To Find Them One Ring To Bring Them All And In The Darkness Bind Them.",
        price='25.33',
        category="Adventure"
        ),
    Book(
        title="Jurassic Park",
        author="Michael Crichton",
        year='1990',
        isbn="9780345538987",
        edition="1st",
        origin="USA",
        book_format="ebook",
        binding="Perfect Binding",
        language="English",
        country="United States",
        pages='448',
        stock='60',
        url_img="https://m.media-amazon.com/images/I/81rBVCDfrgL._AC_UY327_FMwebp_QL65_.jpg",
        description="Jurassic Park Scientists Clone Dinosaur Dna To Create A Theme Park With Extinct Creatures But "
                    "When The Security System Fails The Dinosaurs Escape.",
        price='14.55',
        category="Adventure"
        ),
    Book(
        title='The Treasure Island',
        author='Robert Louis Stevenson',
        year='1883',
        isbn='9780198063267',
        edition='2nd Revised edition',
        origin='United Kingdom',
        book_format='ebook',
        binding='Perfect',
        language='English',
        country='UK',
        pages='304',
        stock='10',
        url_img='https://m.media-amazon.com/images/I/81fvZDUsehL._AC_UY327_FMwebp_QL65_.jpg',
        description="The First-person Story Of Jim Hawkins, Whose Peaceful Life At His Mother's Inn Is Disrupted By "
                    "Pirates Seeking The Treasure Of Captain Flint. Jim Sets Out With Allies To Find It.",
        price='16.98',
        category="Adventure"
        ),
    Book(title='The Call of the Wild',
         author='Jack London',
         year='1903',
         isbn='9780199553976',
         edition='1st Edition',
         origin='United States',
         book_format='ebook',
         binding='Perfect',
         language='English',
         country='USA',
         pages='128',
         stock='7',
         url_img='https://m.media-amazon.com/images/I/81acMmy33yL._AC_UY327_FMwebp_QL65_.jpg',
         description="The Call Of The Wild Follows Buck A Domesticated Dog Who Must Adapt To Survive As An Alaskan "
                     "Sled Dog And Becomes Aleader In The Wild.",
         price='15.95',
         category="Adventure"
         ),
    Book(
        title='The Lost City of the Monkey God',
        author='Douglas Preston',
        year='2017',
        isbn='9781455540013',
        edition='1st Edition',
        origin='United States',
        book_format='ebook',
        binding='Sewn binding',
        language='English',
        country='USA',
        pages='336',
        stock='10',
        url_img='https://m.media-amazon.com/images/I/91m2dauZjCL._AC_UY327_FMwebp_QL65_.jpg',
        description="A Five-hundred-year-old Legend. An Ancient Curse. A Stunning Medical Mystery. And A Pioneering "
                    "Journey Into The Unknown Heart Of The World's Densest Jungle.",
        price='28.46',
        category="Adventure"
        ),
    Book(
        title="The Hobbit",
        author="J.R.R. Tolkien",
        year='1937',
        isbn="9780547928227",
        edition="1st",
        origin="UK",
        book_format="ebook",
        binding="Perfect",
        language="English",
        country="United Kingdom",
        pages='310',
        stock='50',
        url_img="https://m.media-amazon.com/images/I/91M9xPIf10L._AC_UY327_FMwebp_QL65_.jpg",
        description="The Hobbit Bilbo Baggins Embarks On An Epic Adventure With A Group Of Dwarves To Reclaim "
                    "Their Stolen Treasure From A Dragon.",
        price='15.40',
        category="Adventure"
        ),
    Book(
        title='Pride and Prejudice',
        author='Jane Austen',
        year='1813',
        isbn='9780486284736',
        edition='1st Edition',
        origin='United Kingdom',
        book_format='ebook',
        binding='Perfect',
        language='English',
        country='UK',
        pages='352',
        stock='10',
        url_img='https://m.media-amazon.com/images/I/81FOTF7SJvL._AC_UY327_FMwebp_QL65_.jpg',
        description="Jane Austens Classic Love Story Between Elizabeth Bennet And Mr Darcy Where Love Blooms Sometimes "
                    "Against Their Own Pride And Prejudices.",
        price='12.56',
        category="Romance"
        ),
    Book(
        title='Jane Eyre',
        author='Charlotte Bronte',
        year='1847',
        isbn='9780141441146',
        edition='Reprint',
        origin='United Kingdom',
        book_format='ebook',
        binding='Perfect',
        language='English',
        country='UK',
        pages='624',
        stock='5',
        url_img='https://m.media-amazon.com/images/I/911HhiTClmS._AC_UY327_FMwebp_QL65_.jpg',
        description="Jane Eyre Is The Story Of A Young Governess Who Falls In Love With Her Brooding And "
                    "Mysterious Employer Mr Rochester.",
        price='8.99',
        category="Romance"
        ),
    Book(
        title='Wuthering Heights',
        author='Emily Bronte',
        year='1847',
        isbn='9780141439556',
        edition='Reprint',
        origin='United Kingdom',
        book_format='ebook',
        binding='Perfect',
        language='English',
        country='UK',
        pages='416',
        stock='8',
        url_img='https://m.media-amazon.com/images/I/91rViXWBDNL._AC_UY327_FMwebp_QL65_.jpg',
        description="Wuthering Heights Is Emily Brontes Only Novel It Is A Story Of Heathcliff A Dark Outsider Who "
                    "Falls In Love With The Spirited Cathy But Cannot Have Her Destroying Them Both In The Process.",
        price='7.55',
        category="Romance"
        ),
    Book(
        title='Outlander',
        author='Diana Gabaldon',
        year='1991',
        isbn='9780440212560',
        edition='Reprint',
        origin='United States',
        book_format='ebook',
        binding='Perfect',
        language='English',
        country='USA',
        pages='896',
        stock='15',
        url_img='https://m.media-amazon.com/images/I/91tjikkfB6L._AC_UY327_FMwebp_QL65_.jpg',
        description="Outlander Is A Historical Romance Novel By Diana Gabaldon It Follows The Story Of Claire Randall "
                    "A Combat Nurse From 1945 Who Is Transported Back In Time To 1743 Scotland Where She Falls In Love "
                    "With The Young Warrior Jamie Fraser.",
        price='16.99',
        category="Romance"
        ),
    Book(
        title="The Time Traveler's Wife",
        author="Audrey Niffenegger",
        year='2003',
        isbn="9780156029438",
        edition="1st Edition",
        origin="United States",
        book_format="Ebook",
        binding="Paperback",
        language="English",
        country="USA",
        pages='546',
        stock='12',
        url_img="https://m.media-amazon.com/images/I/81ilgC2Cw4S._AC_UY327_FMwebp_QL65_.jpg",
        description="The Time Traveler's Wife Is A Novel About A Man Named Henry Detamble Who Suffers From A Genetic "
                    "Disorder That Causes Him To Time Travel Involuntarily, And His Wife Clare Abshire, Who Has Known "
                    "Him Since She Was Six Years Old.",
        price='12.99',
        category="Romance"
        ),
    Book(
        title='The Fault in Our Stars',
        author='John Green',
        year='2012',
        isbn='9780525478812',
        edition='1st Edition',
        origin='United States',
        book_format='ebook',
        binding='Hardcover',
        language='English',
        country='USA',
        pages='336',
        stock='9',
        url_img='https://m.media-amazon.com/images/I/81a4kCNuH+L._AC_UY327_FMwebp_QL65_.jpg',
        description="The Fault In Our Stars Is A Story About Two Teenagers, Hazel Grace Lancaster And Augustus Waters, "
                    "Who Fall In Love After Meeting At A Cancer Support Group.",
        price='10.99',
        category="Romance"
        ),
    Book(
        title='The Notebook',
        author='Nicholas Sparks',
        year='1996',
        isbn='9780446520802',
        edition='1st Edition',
        origin='United States',
        book_format='ebook',
        binding='Trade Paperback',
        language='English',
        country='USA',
        pages='272',
        stock='5',
        url_img='https://m.media-amazon.com/images/I/81OHCNjv7HL._AC_UY327_FMwebp_QL65_.jpg',
        description="The Notebook Is A Love Story About A Man Named Noah Calhoun Who Falls In Love With A Woman "
                    "Named Allie Hamilton. The Story Is Set In The 1940s In The Coastal Town Of Seabrook, "
                    "North Carolina.",
        price='8.99',
        category="Romance"
        ),
    Book(
        title='Me Before You',
        author='Jojo Moyes',
        year='2012',
        isbn='9780670026609',
        edition='1st Edition',
        origin='United Kingdom',
        book_format='ebook',
        binding='Hardcover',
        language='English',
        country='UK',
        pages='400',
        stock='2',
        url_img='https://m.media-amazon.com/images/I/71B1dTlYH5L._AC_UY327_FMwebp_QL65_.jpg',
        description="Me Before You Is A Story About A Woman Named Louisa Clark Who Becomes A Caregiver For A Man "
                    "Named Will Traynor, Who Is Quadriplegic After A Motorcycle Accident. The Story Follows Their "
                    "Relationship As They Help Each Other See The Beauty In Life.",
        price='14.99',
        category="Romance"
        )
]
